fjelltopp/meerkat_frontend

meerkat_frontend/test/__init__.py

- Adjust current unit tests to use `self.assertEqual` instead of `assert`.
- Add unit tests for epi week functions

Revise unit tests

---

meerkat_frontend/templates/reports/report_jordan_public_health_profile.html

Update contact info on public health report

---

config.py
meerkat_frontend/templates/reports/email_jordan_public_health_profile.html
meerkat_frontend/views/reports.py

Change reports email address to `notifications@moh.gov.jo`

Change Jordan reports email address and subject

---

meerkat_frontend/views/reports.py

This pull request is for referring to the correct email parameter when sending monthly emails.

Refer to correct report config

---

meerkat_frontend/views/technical.py

Testing the new protections given to master branch.

Test pull request. Fixed a style issue.

---

meerkat_frontend/src/files/pages/timeliness.html
meerkat_frontend/src/js/technical/misc.js
meerkat_frontend/src/js/technical/tableManager.js

https://github.com/meerkat-code/madagascar_feedback/issues/34

timeliness matrix, name of location bug and yearly value

---

country_config/null_config.py
country_config/null_technical.json

Reverts meerkat-code/meerkat_frontend#372
This needs to be merged into development not master.

Revert "Issue115"

---

country_config/null_reports.json
country_config/null_technical.json
meerkat_frontend/src/files/pages/completeness.html
meerkat_frontend/src/files/pages/completenessCD.html
meerkat_frontend/src/files/pages/completenessEBS.html
meerkat_frontend/src/files/pages/completenessNCD.html
meerkat_frontend/src/files/pages/timeliness.html
meerkat_frontend/src/files/pages/timelinessCD.html
meerkat_frontend/src/files/pages/timelinessEBS.html
meerkat_frontend/src/files/pages/timelinessNCD.html
meerkat_frontend/src/js/technical/misc.js
meerkat_frontend/src/js/technical/overview.js
meerkat_frontend/src/js/technical/tableManager.js
meerkat_frontend/templates/technical/index.html

Update on the Alerts to be sorted by date insted of index and make sure the indicator result is equal to the order in the config obj

Overview Branch

---

meerkat_frontend/src/js/technical/clinics.js
meerkat_frontend/src/js/technical/tableManager.js

Its contains updates for Rania.

Clinics branch

---

meerkat_frontend/src/files/pages/clinics.html
meerkat_frontend/src/js/technical/clinics.js
meerkat_frontend/src/js/technical/misc.js
meerkat_frontend/templates/explore/index.html
meerkat_frontend/templates/technical/index.html

Remove the pre-existing throbbers from the explore and clinics pages. 
Add the current throbber solution only for the technical and explore parts of the site.
@ZiadFra - I want to fix these throbbers up early today.  Gunnar has given some useful feedback so I've just made the changes myself. Hope that is ok.

Improve throbbers.

---

meerkat_frontend/test/test_messaging.py
meerkat_frontend/views/messaging.py

Tidies up the code a little bit. 
Fixes a bug due to assuming a Nexmo response from hermes sms resource instead of the new AWS response.

Fix the handling of the SMS response.

---

meerkat_frontend/src/files/pages/overview.html
meerkat_frontend/src/js/technical/overview.js
meerkat_frontend/src/sass/_technical.scss
messages.pot
translations/fr/LC_MESSAGES/messages.po

Two updates for the overview page:
- Fix the indicator order 
- Use bootstrap grid in the standard box display.

Overview page refactor

---

.snyk
bower.json
country_config/null_config.py
country_config/null_technical.json
meerkat_frontend/common.py
meerkat_frontend/src/files/pages/disease.html
meerkat_frontend/src/files/pages/mh_diseases.html
meerkat_frontend/src/files/pages/overview.html
meerkat_frontend/src/js/technical/misc.js
meerkat_frontend/src/js/technical/overview.js
meerkat_frontend/src/sass/_technical.scss
meerkat_frontend/templates/includes/js.html
messages.pot
package.json
translations/fr/LC_MESSAGES/messages.po

Re deploying Jordan, primarily for the reason of updating the tablet inventory.

Redeploying Jordan

---

meerkat_frontend/src/js/technical/overview.js

New ways to format the indicator value string that better communicate what the value means. 
The default behaviour is for the "value" column to look like this:

Indicators qfix

---

meerkat_frontend/templates/reports/report_pip.html

Addressing this issue: https://github.com/meerkat-code/meerkat_issues/issues/239

Handle zero division errors in Pip report Jinja2 template.

---

meerkat_frontend/templates/base.html

This is to fix issue https://github.com/meerkat-code/meerkat_issues/issues/256

Fix nav bar title link.

---

meerkat_frontend/src/js/technical/tableManager.js

We're currently out of sync with available medicine kits in Somalia clinic so I've decided to hide available stock for now in frontend.

Removed prescriptions stock and added prescription category to explore.

---

meerkat_frontend/src/files/pages/consultations.html
meerkat_frontend/src/js/technical/chartManager.js
meerkat_frontend/src/js/technical/misc.js
meerkat_frontend/src/js/technical/tableManager.js
translations/fr/LC_MESSAGES/messages.po

* First draft of consultations tab
* All working all dancing Consultations tab
* removed console prints and similar comments
* indentation
* var init bug fixed
* reverted autoformatting of html file which ended up in tears
* fixxed untranslated S for Week
* Corrected for a name change in API
* consultations translations
* missing translations of completeness and consultations

Consultations tab (#429)

---

meerkat_frontend/src/files/pages/diseases.html
meerkat_frontend/templates/technical/index.html
meerkat_frontend/templates/technical/tab_options.html

This PR should enable the additional options in country_technical.json file to be used in the tab templates.

Added additional options for tab html pages.

---

meerkat_frontend/src/js/explore/explore.js
meerkat_frontend/templates/explore/index.html

When location is chosen as a variable for a timeline, we need to amend the api query. Instead of location number we request `tot_1` and ask to limit results to the supplemented location.

Timeline now appears when selecting a location

---

meerkat_frontend/src/js/technical/mapManager.js

Fix for the maps in technical site

remove hard coded MapBox account ID form map manager

---

meerkat_frontend/src/files/pages/consultations.html
meerkat_frontend/src/js/technical/misc.js
meerkat_frontend/src/js/technical/tableManager.js

Added consultation matrix alike completeness matrix. Some texts might need to be translated but we can do it after adding to dev.

Consultations matrix

---

translations/fr/LC_MESSAGES/messages.po

* consultations tab
* word <<year>> in tables
* typo

Translations fix apr18 (#453)

---

.snyk
meerkat_frontend/src/js/technical/mapManager.js
package.json

Forgot about incident maps available for Madagascar.

Clear of old map for incident maps.

---

meerkat_frontend/src/files/pages/completeness.html
meerkat_frontend/src/js/technical/misc.js
meerkat_frontend/src/js/technical/tableManager.js

Completeness Matrix Improvements
https://github.com/fjelltopp/madagascar_feedback/issues/125#issuecomment-447562017

Mad issue 125

---

meerkat_frontend/src/files/pages/vaccination.html
meerkat_frontend/src/js/explore/explore.js

Fixing the vaccination table bug as specified in madagascar_feedback issue 127:
https://github.com/fjelltopp/madagascar_feedback/issues/127

Mad issue127

---

meerkat_frontend/src/js/technical/tableManager.js

The completeness matrix was not showing any week 1 data during week 2. The column was missing from the table because of the way we were looping though the weeks.  It was a bit fiddly but I think I've managed to correct the issue.

Fix completeness matrix.

---

meerkat_frontend/src/js/technical/chartManager.js
meerkat_frontend/src/js/technical/locationManager.js
meerkat_frontend/src/js/technical/overview.js
meerkat_frontend/src/js/technical/tableManager.js
meerkat_frontend/templates/reports/index.html
messages.pot
translate.py
translations/fr/LC_MESSAGES/messages.po

I'm not sure If I committed correct files for translations @jonathansberry ?
That should finalise issue https://github.com/fjelltopp/car_feedback/issues/15 for now.

CAR overview frontend

---

meerkat_frontend/src/js/technical/tableManager.js

Fixes issue https://fjelltopp.atlassian.net/browse/CAR-33?atlOrigin=eyJpIjoiOGRjNTU1OGVkMTQwNDJkYzgyMDUyNDg1YTI2MzliOWIiLCJwIjoiaiJ9

fix completeness matrix bug

---

meerkat_frontend/src/files/pages/vaccination.html

Fix data download for overview vaccination timeline table

Issue car 50
